---
name: "Terraform Pull Request"

on:
  pull_request:

jobs: 
  pull_request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Terrform Install
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.1.7"
      - name: Terrform Plan
        run: terraform init

